In [ ]:
import warnings
warnings.filterwarnings('ignore')
import pandas as pd #provides data structures to quickly analyze data
import numpy as np
import matplotlib.pyplot as plot
import seaborn as sns
from sklearn.utils import resample
from imblearn.over_sampling import RandomOverSampler
from sklearn.impute import KNNImputer
from sklearn.preprocessing import LabelEncoder
sns.set()

In [ ]:
dataset=pd.read_excel("Investment Pattern.xlsx")

In [ ]:
dataset.head(10)

,Timestamp,Name:,Age Group,Gender,Profession,Do you make investments?,What kind of investments do you make?,On a scale of 1-5 where do you consider your knowledge of investments,What are your expectations from the investments you are currently making,What is your main reason for investing ? (one word/one line answer),Why do you not invest in other options?,What are your views on the recent boom in Crypto and NFTs?,Why do you not invest?
0,2022-02-17 15:47:16.472,RAJESH SHETH,41-60 years,Male,Business,Yes,"Gold, PPF, Mutual Funds, Equity Shares, FDs",3.0,Long Term returns,Security,"High Values, High Risks, higher Maintenance co...",Government Policy not clear.,NaN
1,2022-02-17 15:47:38.898,Parth nagda,16-25 years,Male,Student,Yes,"Mutual Funds, Equity Shares",4.0,Long Term returns,Yeh hi future hai,N,NaN,NaN
2,2022-02-17 15:48:33.798,NaN,16-25 years,Other,Self employed,Yes,Sex toys,5.0,Short Term returns,Create more videos,Will expend soon,Good,NaN
3,2022-02-17 15:54:04.252,Vansh Matalia,16-25 years,Male,Student,Yes,"Gold, PPF, Mutual Funds, Equity Shares, FDs, R...",4.0,"Short Term returns, Long Term returns",Returns,"Gold, mutual funds are safe investments",NaN,NaN
4,2022-02-17 15:55:21.924,Trusar Sheth,41-60 years,Male,Business,Yes,Equity Shares,3.0,Long Term returns,Financial security,Not comfortable,None,NaN
5,2022-02-17 16:02:20.750,Kanchan Merani,41-60 years,Female,Home maker,Yes,"Gold, PPF, FDs",2.0,Long Term returns,Security,Don't feel safe,No idea,NaN
6,2022-02-17 16:04:31.725,Seema Duvedi,41-60 years,Female,Homemaker,No,NaN,NaN,NaN,NaN,NaN,NaN,Husband takes care of investments
7,2022-02-17 16:24:03.249,Loukik Khandare,16-25 years,Male,Student,Yes,"Gold, Equity Shares",5.0,Mixed portfolio with short and long term returns.,Creating wealth in the long term,Rate of returns is higher in equity.,I find it nonsense. There's no regulatory body...,NaN
8,2022-02-17 16:52:41.963,SHAILESH JAIN,41-60 years,Male,Employed,Yes,"Mutual Funds, Equity Shares, EPF",5.0,Long Term returns,EARNING MORE THAN NORMAL FD RETURNS.,LESS RETURNS,NaN,NaN
9,2022-02-17 17:13:49.587,Naman,16-25 years,Male,Student,Yes,"Mutual Funds, Equity Shares",3.0,Long Term returns,Cover up my Student Loans,I invest in things I understand,OverHyped,NaN

In [ ]:
dataset = dataset.drop(['Timestamp','Name:'],axis =1)

In [ ]:
dataset.head(10)

,Age Group,Gender,Profession,Do you make investments?,What kind of investments do you make?,On a scale of 1-5 where do you consider your knowledge of investments,What are your expectations from the investments you are currently making,What is your main reason for investing ? (one word/one line answer),Why do you not invest in other options?,What are your views on the recent boom in Crypto and NFTs?,Why do you not invest?
0,41-60 years,Male,Business,Yes,"Gold, PPF, Mutual Funds, Equity Shares, FDs",3.0,Long Term returns,Security,"High Values, High Risks, higher Maintenance co...",Government Policy not clear.,NaN
1,16-25 years,Male,Student,Yes,"Mutual Funds, Equity Shares",4.0,Long Term returns,Yeh hi future hai,N,NaN,NaN
2,16-25 years,Other,Self employed,Yes,Sex toys,5.0,Short Term returns,Create more videos,Will expend soon,Good,NaN
3,16-25 years,Male,Student,Yes,"Gold, PPF, Mutual Funds, Equity Shares, FDs, R...",4.0,"Short Term returns, Long Term returns",Returns,"Gold, mutual funds are safe investments",NaN,NaN
4,41-60 years,Male,Business,Yes,Equity Shares,3.0,Long Term returns,Financial security,Not comfortable,None,NaN
5,41-60 years,Female,Home maker,Yes,"Gold, PPF, FDs",2.0,Long Term returns,Security,Don't feel safe,No idea,NaN
6,41-60 years,Female,Homemaker,No,NaN,NaN,NaN,NaN,NaN,NaN,Husband takes care of investments
7,16-25 years,Male,Student,Yes,"Gold, Equity Shares",5.0,Mixed portfolio with short and long term returns.,Creating wealth in the long term,Rate of returns is higher in equity.,I find it nonsense. There's no regulatory body...,NaN
8,41-60 years,Male,Employed,Yes,"Mutual Funds, Equity Shares, EPF",5.0,Long Term returns,EARNING MORE THAN NORMAL FD RETURNS.,LESS RETURNS,NaN,NaN
9,16-25 years,Male,Student,Yes,"Mutual Funds, Equity Shares",3.0,Long Term returns,Cover up my Student Loans,I invest in things I understand,OverHyped,NaN

In [ ]:
dataset=dataset[['Age Group','Profession','Gender','Do you make investments?']]

In [ ]:
dataset.head()

     Age Group     Profession Gender Do you make investments?
0  41-60 years       Business   Male                      Yes
1  16-25 years        Student   Male                      Yes
2  16-25 years  Self employed  Other                      Yes
3  16-25 years        Student   Male                      Yes
4  41-60 years       Business   Male                      Yes

In [ ]:
df=dataset['Profession'].str.get_dummies(sep=', ')
print(df)

     Business  Chartered accountant   Consultant   Employed  Ex bank staff   \
0           1                      0            0         0               0
1           0                      0            0         0               0
2           0                      0            0         0               0
3           0                      0            0         0               0
4           1                      0            0         0               0
..        ...                    ...          ...       ...             ...
195         1                      0            0         0               0
196         0                      0            0         0               0
197         0                      0            0         1               0
198         0                      1            0         0               0
199         0                      0            0         1               0

     Freelance writer  Home maker  Home maker   Homemaker   Housewife  \
0                   0           0            0           0          0
1                   0           0            0           0          0
2                   0           0            0           0          0
3                   0           0            0           0          0
4                   0           0            0           0          0
..                ...         ...          ...         ...        ...
195                 0           0            0           0          0
196                 0           0            0           0          0
197                 0           0            0           0          0
198                 0           0            0           0          0
199                 0           0            0           0          0

     Retired  Retired Teacher  Self employed  Self employed   Student  Trading
0          0                0              0               0        0        0
1          0                0              0               0        1        0
2          0                0              1               0        0        0
3          0                0              0               0        1        0
4          0                0              0               0        0        0
..       ...              ...            ...             ...      ...      ...
195        0                0              0               0        0        0
196        0                0              0               0        1        0
197        0                0              0               0        0        0
198        0                0              0               0        0        0
199        0                0              0               0        0        0

[200 rows x 16 columns]

In [ ]:
df["Employed"] = df["Employed"] + df["Self employed"] + df["Self employed "] + df["Chartered accountant "] + df["Consultant "]
df["OtherProfession"] = df["Home maker"] + df["Home maker "] + df["Housewife"] + df["Freelance writer"] + df["Trading"] + df["Ex bank staff "] + df["Retired"] + df["Retired Teacher"] + df["Trading"]
df=df[["Employed","OtherProfession","Business","Student"]]

In [ ]:
dataset=dataset.drop(['Profession'],axis=1)
dataset = pd.concat([dataset, df], axis = 1)

In [ ]:
dataset.head()

,Age Group,Gender,Do you make investments?,Employed,OtherProfession,Business,Student
0,41-60 years,Male,Yes,0,0,1,0
1,16-25 years,Male,Yes,0,0,0,1
2,16-25 years,Other,Yes,1,0,0,0
3,16-25 years,Male,Yes,0,0,0,1
4,41-60 years,Male,Yes,0,0,1,0

In [ ]:
dataset.isnull().sum()

Age Group                   0
Gender                      0
Do you make investments?    0
Employed                    0
OtherProfession             0
Business                    0
Student                     0
dtype: int64

In [ ]:
from google.colab import files

In [ ]:
dataset.to_excel('Investment Pattern General.xlsx')

In [ ]:
files.download('Investment Pattern General.xlsx')